apiVersion: v1
kind: Pod
metadata:
  name: k6node ## since this file is cached as Jenkins node template, change this name when below attributes are updated, otherwise it will keep using old ones!!! Need to update Jenkinsfile also.
  labels:
    app: k6
spec:
  namespace: jenkins
    template:
      metadata:
        # These are important, for Prometheus to pick up the data
        annotations:
          prometheus.io/port: '2112'
          prometheus.io/scrape: 'true'
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          namespace: jenkins
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - k6
                  - k6node
  containers:
  - name: k6
    image: loadimpact/k6:latest         #your.docker_registry.com/your_org/k6:your_image_version
    command: ["tail","-f","/dev/null"]
    resources:
      requests:
          cpu: "100m"
          memory: "256Mi"
    tty: true
    securityContext: ## <-- When define USER in Dockerfile, securityContext should be added with root user, so that shell script will not hang in container
      runAsUser: 0
  - name: k6-exporter
    image: ghcr.io/benc-uk/k6-prometheus-exporter:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 2112
